services:
  backend:
    image: vinhtuong2712/backend:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    image: vinhtuong2712/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
