name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Backend ENV
        run: |
          cd backend
          echo "${{ secrets.BACKEND_ENV }}" > .env

      - name: Setup Frontend ENV
        run: |
          cd frontend
          echo "${{ secrets.FRONTEND_ENV }}" > .env

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          build-args: |
            VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Trigger Backend Deployment
        run: |
          curl -X GET ${{ secrets.RENDER_BACKEND_DEPLOY_URL }}

      - name: Trigger Frontend Deployment
        run: |
          curl -X GET ${{ secrets.RENDER_FRONTEND_DEPLOY_URL }}
